# MySQL properties
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb1?verifyServerCertificate=false&useSSL=false&requireSSL=false&useLegacyDatetimeCode=false&amp&serverTimezone=UTC
    username: root
    password: root
# Hibernate properties
  jpa:
    properties:
      hibernate:
        show_sql: true
        dialect:  org.hibernate.dialect.MySQLDialect
        hbm2ddl.auto: update
# hiddenHttpMethodFilter properties
  mvc:
    hiddenmethod:
      filter:
        enabled: true